/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SheLeads {
  export type ActionPlanStruct = { id: BigNumberish; content: string };

  export type ActionPlanStructOutput = [id: bigint, content: string] & {
    id: bigint;
    content: string;
  };

  export type ProfessionalProfileStruct = { id: BigNumberish; content: string };

  export type ProfessionalProfileStructOutput = [
    id: bigint,
    content: string
  ] & { id: bigint; content: string };

  export type RecommendationStruct = { id: BigNumberish; content: string };

  export type RecommendationStructOutput = [id: bigint, content: string] & {
    id: bigint;
    content: string;
  };
}

export interface SheLeadsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addActionPlan"
      | "addProfessionalProfile"
      | "addRecommendation"
      | "getActionPlan"
      | "getProfessionalProfile"
      | "getRecommendation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddActionPlan"
      | "AddProfessionalProfile"
      | "AddRecommendation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addActionPlan",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProfessionalProfile",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addRecommendation",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActionPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfessionalProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecommendation",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addActionPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProfessionalProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRecommendation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActionPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProfessionalProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecommendation",
    data: BytesLike
  ): Result;
}

export namespace AddActionPlanEvent {
  export type InputTuple = [userAddress: AddressLike];
  export type OutputTuple = [userAddress: string];
  export interface OutputObject {
    userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddProfessionalProfileEvent {
  export type InputTuple = [userAddress: AddressLike];
  export type OutputTuple = [userAddress: string];
  export interface OutputObject {
    userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddRecommendationEvent {
  export type InputTuple = [userAddress: AddressLike];
  export type OutputTuple = [userAddress: string];
  export interface OutputObject {
    userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SheLeads extends BaseContract {
  connect(runner?: ContractRunner | null): SheLeads;
  waitForDeployment(): Promise<this>;

  interface: SheLeadsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addActionPlan: TypedContractMethod<
    [_recommendationId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;

  addProfessionalProfile: TypedContractMethod<
    [_content: string],
    [void],
    "nonpayable"
  >;

  addRecommendation: TypedContractMethod<
    [_professionalProfileId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;

  getActionPlan: TypedContractMethod<
    [_recommendationId: BigNumberish],
    [SheLeads.ActionPlanStructOutput],
    "view"
  >;

  getProfessionalProfile: TypedContractMethod<
    [],
    [SheLeads.ProfessionalProfileStructOutput],
    "view"
  >;

  getRecommendation: TypedContractMethod<
    [_professionalProfile: BigNumberish],
    [SheLeads.RecommendationStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addActionPlan"
  ): TypedContractMethod<
    [_recommendationId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProfessionalProfile"
  ): TypedContractMethod<[_content: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addRecommendation"
  ): TypedContractMethod<
    [_professionalProfileId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActionPlan"
  ): TypedContractMethod<
    [_recommendationId: BigNumberish],
    [SheLeads.ActionPlanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProfessionalProfile"
  ): TypedContractMethod<
    [],
    [SheLeads.ProfessionalProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecommendation"
  ): TypedContractMethod<
    [_professionalProfile: BigNumberish],
    [SheLeads.RecommendationStructOutput],
    "view"
  >;

  getEvent(
    key: "AddActionPlan"
  ): TypedContractEvent<
    AddActionPlanEvent.InputTuple,
    AddActionPlanEvent.OutputTuple,
    AddActionPlanEvent.OutputObject
  >;
  getEvent(
    key: "AddProfessionalProfile"
  ): TypedContractEvent<
    AddProfessionalProfileEvent.InputTuple,
    AddProfessionalProfileEvent.OutputTuple,
    AddProfessionalProfileEvent.OutputObject
  >;
  getEvent(
    key: "AddRecommendation"
  ): TypedContractEvent<
    AddRecommendationEvent.InputTuple,
    AddRecommendationEvent.OutputTuple,
    AddRecommendationEvent.OutputObject
  >;

  filters: {
    "AddActionPlan(address)": TypedContractEvent<
      AddActionPlanEvent.InputTuple,
      AddActionPlanEvent.OutputTuple,
      AddActionPlanEvent.OutputObject
    >;
    AddActionPlan: TypedContractEvent<
      AddActionPlanEvent.InputTuple,
      AddActionPlanEvent.OutputTuple,
      AddActionPlanEvent.OutputObject
    >;

    "AddProfessionalProfile(address)": TypedContractEvent<
      AddProfessionalProfileEvent.InputTuple,
      AddProfessionalProfileEvent.OutputTuple,
      AddProfessionalProfileEvent.OutputObject
    >;
    AddProfessionalProfile: TypedContractEvent<
      AddProfessionalProfileEvent.InputTuple,
      AddProfessionalProfileEvent.OutputTuple,
      AddProfessionalProfileEvent.OutputObject
    >;

    "AddRecommendation(address)": TypedContractEvent<
      AddRecommendationEvent.InputTuple,
      AddRecommendationEvent.OutputTuple,
      AddRecommendationEvent.OutputObject
    >;
    AddRecommendation: TypedContractEvent<
      AddRecommendationEvent.InputTuple,
      AddRecommendationEvent.OutputTuple,
      AddRecommendationEvent.OutputObject
    >;
  };
}
